# -*- coding: utf-8 -*-
"""Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDsIWyGr8f7s0bOVL2Xa8NQK53ngPWUL
"""

try:
    a = int(input("Enter a number: "))
    b = int(input("Enter another number: "))
    result = a / b
    print("Result is:", result)

except ZeroDivisionError:
    print("Error: you cannot divide by zero")

except ValueError:
    print("Error: Invalid input, please enter an integer")

print("Program continues")


try:
    x = int(input("Enter number: "))
    y = 10 / x
    print("Result:", y)

except ZeroDivisionError:
    print("Error: Division by zero")

except ValueError:
    print("Error: Invalid input")


try:
    num = int(input("Enter a number: "))
except ValueError:
    print("Oops! Invalid input")
else:
    print("You entered:", num)


try:
    file = open("data.txt", "r")
    read_data = file.read()
    print(read_data)

except FileNotFoundError:
    print("File not found")

finally:
    print("Execution completed")


try:
    age = int(input("Enter age: "))
    if age < 18:
        raise Exception("Age must be at least 18!")
    print("Age accepted")

except Exception as e:
    print("Error:", e)

def get_number(prompt):
    while True:
        try:
            value = int(input(prompt))
            return value
        except ValueError:
            print("Invalid input. Try again!")

num1 = get_number("Enter first number: ")
num2 = get_number("Enter second number: ")

try:
    res = num1 / num2

except ZeroDivisionError:
    print("Cannot divide by zero")

else:
    print("Division Result:", res)

finally:
    print("Execution done. Thanks!")

