# -*- coding: utf-8 -*-
"""File handling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CnyML1xTTEo3s6ZubkMQvdd7L29urE5d
"""

file = open("student.txt", "w")
file.write("Srujana 20\n")
file.write("Ganga 28\n")
file.close()

file = open("student.txt", "r")
content = file.read()
print("Reading using open():")
print(content)
file.close()

print("Reading using with open():")
with open("student.txt", "r") as file:
    print(file.read())

with open("data.txt", "w") as file:
    file.write("Welcome to AI class")

print("Data saved successfully!")