# -*- coding: utf-8 -*-
"""Ratelimiting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HCJER6EFt47KEI8C9_HxBm3f4V0ljg8y
"""

import time

requests = {}
LIMIT = 5
TIME_WINDOW = 60

def is_allowed(user_id):
    current_time = time.time()

    if user_id not in requests:
        requests[user_id] = []

    requests[user_id] = [
        t for t in requests[user_id]
        if current_time - t < TIME_WINDOW
    ]

    if len(requests[user_id]) < LIMIT:
        requests[user_id].append(current_time)
        return True
    else:
        return False


user = "user1"

for i in range(7):
    print(i + 1, is_allowed(user))
    time.sleep(1)

import time

class TokenBucket:
    def __init__(self, capacity, refill_rate):
        self.capacity = capacity
        self.refill_rate = refill_rate
        self.tokens = capacity
        self.last_refill_time = time.time()

    def allow(self):
      now = time.time()
      # refill tokens based on elapsed time
      elapsed = now-self.last_refill_time
      self.tokens = min(self.capacity, self.tokens+elapsed*self.refill_rate)
      self.last_refill_time = now

      if self.tokens >= 1:
        self.tokens -= 1
        return True
      else:
        return False

backspace = TokenBucket(capacity=5, refill_rate=1)

for i in range(10):
  if backspace.allow():
    print(f"{time.time():.2f} -allowed{i}")
  else:
    print(f"{time.time():.2f} -not allowed{i}")
  time.sleep(0.5)